org: firsttracksolutiontechnologies
app: jupiterxpress
service: jupiterXpress

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: api
  environment:
    AWS_ACCESS_KEY_ID_ : ${env:AWS_ACCESS_KEY_ID_}
    AWS_REGION_ : ${env:AWS_REGION_}
    AWS_SECRET_ACCESS_KEY_ : ${env:AWS_SECRET_ACCESS_KEY_}
    DB_HOST : ${env:DB_HOST}
    DB_NAME : ${env:DB_NAME}
    DB_PASSWORD : ${env:DB_PASSWORD}
    DB_USER : ${env:DB_USER}
    EMAIL_HOST : ${env:EMAIL_HOST}
    EMAIL_PASSWORD : ${env:EMAIL_PASSWORD}
    EMAIL_PORT : ${env:EMAIL_PORT}
    EMAIL_SECURE : ${env:EMAIL_SECURE}
    EMAIL_USER : ${env:EMAIL_USER}
    JWT_SECRET : ${env:JWT_SECRET}
    NODE_ENV : ${env:NODE_ENV}
functions:
  app:
    handler: app.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
plugins:
  # - serverless-plugin-split-stacks
  - serverless-offline
  - serverless-dotenv-plugin